#pragma once

const int CORAL_LAUNCHER_FLYWHEEL_RIGHT_CAN_ID = 43;
const int CORAL_LAUNCHER_FLYWHEEL_LEFT_CAN_ID = 42;
const int CORAL_LAUNCHER_INDEXER_RIGHT_CAN_ID = 40;
const int CORAL_LAUNCHER_INDEXER_LEFT_CAN_ID = 41;

const int ALGAE_REMOVER_ARM_CAN_ID = 51;
const int ALGAE_REMOVER_WHEEL_CAN_ID = 50;

const int CLIMBER_WINCH_CAN_ID = 30;
