name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
    - uses: actions/checkout@v5
    - name: Build robot code
      run: |
        chmod +x gradlew
        ./gradlew build
